import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { Navigate, useLocation, useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import { AppShellRuntime } from '@etendosoftware/app-shell-core/runtime';
import { ObservabilityProvider } from '@etendosoftware/app-shell-core/observability';
import { trackMcpConnectTabSelected } from '@/lib/mcpConnectTelemetry.js';
import AppLayout from './layout/AppLayout.jsx';
import { buildMenuGroups, buildWindowMap } from './windows/registry.js';
import { buildRuntimeRoutes } from './runtime-routes.jsx';
import { createMockFetch } from './lib/mockFetch.js';
import { useLocaleState } from './i18n/useLocaleState.js';
import { useLocaleDictionaries } from './i18n/useLocaleDictionaries.js';
import { useServiceWorker } from './hooks/useServiceWorker.js';
import { useInstalledApps } from './hooks/useInstalledApps.js';
import { useAppStoreUnlock, attachKeySequenceWatcher } from './hooks/useAppStoreUnlock.js';
import { buildOnboardingReturnTo } from './lib/oauthReturnTo.js';
import { ObservabilityRouteTracker } from './lib/observability/RouteTracker.jsx';
import { SurveyModal } from './components/survey/SurveyModal.jsx';
import { useSurveyEngine } from './hooks/useSurveyEngine.js';
// ETP-4300: the full locale dictionaries are no longer bundled eagerly. Only the
// active locale's sliced "core" (the dict minus the per-window `fields` monolith)
// is lazy-loaded below; per-window field labels ride each window's lazy chunk (see
// WindowLoader). Cores are generated by the slice-labels Vite plugin, which runs
// the slicer from @etendosoftware/schema-forge-cli (gitignored build artifacts).
const coreLoaders = import.meta.glob('./locales/generated/core.*.json');

function detectBasePath() {
  const envBase = import.meta.env.VITE_API_BASE;
  const path = window.location.pathname;
  const webIdx = path.indexOf('/web/');

  if (envBase) {
    const routerBase = webIdx !== -1
      ? `${path.substring(0, webIdx)}/${path.substring(webIdx + 1).split('/').slice(0, 2).join('/')}`
      : '/';
    return { apiBase: envBase, routerBase };
  }

  if (webIdx === -1) return { apiBase: '', routerBase: '/' };
  const contextPath = path.substring(0, webIdx);
  const moduleSegment = path.substring(webIdx + 1).split('/').slice(0, 2).join('/');
  return {
    apiBase: contextPath,
    routerBase: `${contextPath}/${moduleSegment}`,
  };
}

const { apiBase, routerBase } = detectBasePath();
const API_BASE_URL = import.meta.env.VITE_MOCK === 'true'
  ? `${apiBase}/api`
  : `${apiBase}/sws/neo`;

// ETP-4520 — resolves the per-window access tier + named capability flags for
// the current session via the SFWindowAccessMap webhook. Passed into
// AuthProvider (via the `auth` prop bag below) as `fetchWindowAccess`, which
// calls it every time a role is selected (see AuthContext.jsx in
// @etendosoftware/app-shell-core). Fails closed on any error — returning
// `null` leaves AuthProvider's existing ({}) windowAccess/capabilities maps in
// place, which useWindowAccess/useHasCapability both treat as "no access".
// A valid access-map payload always carries at least one of these two keys
// (see SFWindowAccessMap.java — both are always present together, but this
// only requires one so a future partial/evolving shape isn't rejected).
function looksLikeWindowAccessPayload(value) {
  return !!value && typeof value === 'object' && !Array.isArray(value)
    && ('windowAccess' in value || 'capabilities' in value);
}

export async function fetchWindowAccess(session) {
  try {
    // Reached via `/sws/neo/windowaccessmap` (NEO Headless's own JWT auth), not
    // `/webhooks/SFWindowAccessMap` — the Webhooks module additionally requires a
    // per-(webhook, role) grant row in SMFWHE_DEFINEDWEBHOOK_ROLE, which
    // `update.database` wipes back to its XML baseline. See NeoGoWebhookBridge's
    // class javadoc in com.etendoerp.go for the full rationale. Same backend
    // Java class (SFWindowAccessMap) and response shape either way, only the
    // transport changed.
    const res = await fetch(`${apiBase}/sws/neo/windowaccessmap`, {
      method: 'GET',
      credentials: 'include',
    });
    if (!res.ok) return null;
    const data = await res.json();
    // Webhook responses in this app are inconsistent about wrapping the
    // payload — some (the `?name=`-style POST webhooks, e.g. SFListMenu) nest
    // it as a JSON string under `data.result`; this GET webhook may or may not.
    // Handle all shapes defensively rather than assuming one:
    //  - `data.result` is a JSON string  -> parse it (today's real shape,
    //    see SFWindowAccessMap.java's `responseVars.put("result", ...)`).
    //  - `data.result` is already a plain object -> use it directly.
    //  - no `result` key -> `data` itself may already be the unwrapped
    //    `{windowAccess, capabilities}` payload; use it only if it looks
    //    right, otherwise fail closed (return `null`) rather than handing
    //    AuthProvider the wrong shape (e.g. the outer `{result: ...}`
    //    wrapper itself, which would silently deny every window/field).
    if (typeof data?.result === 'string') {
      try { return JSON.parse(data.result); } catch { return null; }
    }
    if (data?.result && typeof data.result === 'object' && !Array.isArray(data.result)) {
      return data.result;
    }
    if (looksLikeWindowAccessPayload(data)) {
      return data;
    }
    return null;
  } catch {
    return null;
  }
}

// ETP-4576 — restores the backend-managed session on boot. Passed into
// AuthProvider (via the `auth` prop bag below) as `restoreSession`, which calls
// it once on mount: a resolved payload ({account, environment, roleList,
// csrfToken}) becomes the authenticated session, anything falsy means "no
// session" and the shell drops to `anonymous`.
//
// The security point of the task (SEC-10): the browser never holds a bearer
// token, so this authenticates purely with the `__Host-` session cookie —
// `credentials: 'include'` and NO Authorization header. Fails closed (null) on
// the 401 for "no session", a network error, or an unparsable body, matching
// fetchWindowAccess's convention above.
//
// NOTE: etendo-go-core's onboarding api.js has its own `fetchSession` doing the
// same call for the (pre-session) onboarding flow. Consolidating both into
// app-shell-core is a natural follow-up; kept separate here to avoid making the
// shell depend on the onboarding package for a platform-level auth concern.
export async function restoreSession() {
  try {
    const res = await fetch(`${apiBase}/sws/go/session`, {
      method: 'GET',
      credentials: 'include',
    });
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

async function loadAllMockData() {
  const modules = await Promise.all([
    import('@generated/sales-order/custom/mockData.js'),
    import('@generated/business-partner/generated/web/business-partner/mockData.js'),
    import('@generated/business-partner-category/generated/web/business-partner-category/mockData.js'),
    import('@generated/warehouse/generated/web/warehouse/mockData.js'),
    import('@generated/price-list/generated/web/price-list/mockData.js'),
    import('@generated/payment-term/generated/web/payment-term/mockData.js'),
    import('@generated/product/generated/web/product/mockData.js'),
    import('@generated/product-category/generated/web/product-category/mockData.js'),
    import('@generated/tax/generated/web/tax/mockData.js'),
    import('@generated/user/generated/web/user/mockData.js'),
    import('@generated/purchase-order/generated/web/purchase-order/mockData.js'),
    import('@generated/goods-receipt/generated/web/goods-receipt/mockData.js'),
    import('@generated/return-to-vendor-shipment/generated/web/return-to-vendor-shipment/mockData.js'),
    import('@generated/physical-inventory/generated/web/physical-inventory/mockData.js'),
    import('@generated/internal-consumption/generated/web/internal-consumption/mockData.js'),
    import('@generated/goods-movements/generated/web/goods-movements/mockData.js'),
    import('@generated/warehouse-storage-bins/generated/web/warehouse-storage-bins/mockData.js'),
    import('@generated/sales-quotation/custom/mockData.js'),
    import('@generated/goods-shipment/custom/mockData.js'),
    import('@generated/return-material-receipt/generated/web/return-material-receipt/mockData.js'),
    import('@generated/sales-invoice/custom/mockData.js'),
    import('@generated/purchase-invoice/generated/web/purchase-invoice/mockData.js'),
    import('@generated/payment-in/custom/mockData.js'),
    import('@generated/payment-out/generated/web/payment-out/mockData.js'),
    import('@generated/chart-of-accounts/generated/web/chart-of-accounts/mockData.js'),
    import('@generated/simple-g-l-journal/generated/web/simple-g-l-journal/mockData.js'),
    import('@generated/assets/generated/web/assets/mockData.js'),
    import('@generated/amortization/generated/web/amortization/mockData.js'),
    import('@generated/deal/generated/web/deal/mockData.js'),
    import('@generated/activity/generated/web/activity/mockData.js'),
    import('@generated/lead/generated/web/lead/mockData.js'),
    import('@generated/employee/generated/web/employee/mockData.js'),
    import('@generated/time-tracking/generated/web/time-tracking/mockData.js'),
    import('@generated/absence/generated/web/absence/mockData.js'),
    import('@generated/project/generated/web/project/mockData.js'),
    import('@generated/document/generated/web/document/mockData.js'),
    import('@generated/recurring-invoice/generated/web/recurring-invoice/mockData.js'),
    import('@generated/fiscal-config/custom/mockData.js'),
    import('@generated/fiscal-monitor/custom/mockData.js'),
    import('@generated/fiscal-models/custom/mockData.js'),
    import('@generated/conversion-rates/generated/web/conversion-rates/mockData.js'),
    import('@generated/conversion-rate-downloader-log/generated/web/conversion-rate-downloader-log/mockData.js'),
    import('@generated/open-close-period-control/generated/web/open-close-period-control/mockData.js'),
    import('@generated/asset-group/generated/web/asset-group/mockData.js'),
    import('@generated/general-ledger-configuration/generated/web/general-ledger-configuration/mockData.js'),
    import('@generated/tax-category/generated/web/tax-category/mockData.js'),
  ]);

  const merged = {};
  for (const mod of modules) {
    for (const [key, value] of Object.entries(mod)) {
      if (key !== 'default') {
        merged[key] = value;
      }
    }
  }
  return merged;
}

function UnauthenticatedRedirect() {
  const location = useLocation();
  return (
    <Navigate
      to={buildOnboardingReturnTo(location)}
      replace
      data-testid="Navigate__ecaf3f" />
  );
}

function AppStoreKeyWatcher() {
  const navigate = useNavigate();
  useEffect(() => {
    return attachKeySequenceWatcher({
      onUnlock: () => {
        toast.success('App Store unlocked', { description: 'Type "playstoreoff" to hide it again.' });
        navigate('/app-store');
      },
      onLock: () => toast('App Store hidden'),
    });
  }, [navigate]);
  return null;
}

function ServiceWorkerManager() {
  const location = useLocation();
  const { checkForUpdate } = useServiceWorker();
  useEffect(() => {
    checkForUpdate();
  }, [location.pathname, checkForUpdate]);
  return null;
}

function SurveyManager() {
  const { activeSurvey, handleRespond, handleClose, handleDismiss } = useSurveyEngine();
  if (!activeSurvey) return null;
  return createPortal(
    <SurveyModal
      survey={activeSurvey}
      open={!!activeSurvey}
      onRespond={handleRespond}
      onClose={handleClose}
      onDismiss={handleDismiss}
      data-testid="SurveyModal__ecaf3f" />,
    document.body,
  );
}

export default function App() {
  const installedApps = useInstalledApps();
  const appStoreUnlocked = useAppStoreUnlock();
  // NOTE: role-based filtering is NOT applied here. `App` itself renders above
  // `AppShellRuntime`'s internal AuthProvider (see main.jsx / this component's own
  // JSX below), so `useAuth()` — and anything built on it, like useRoleMenu() —
  // cannot be called at this level. It's applied one level down in AppLayout.jsx,
  // which IS inside that provider (same place SideMenu already safely calls
  // useAuth() today).
  const menuGroups = buildMenuGroups(installedApps, { appStoreUnlocked });
  const [windowMap] = useState(() => buildWindowMap());
  const [locale, setLocale] = useLocaleState();
  const { dictionaries, renderedLocale } = useLocaleDictionaries(locale, coreLoaders);

  useEffect(() => {
    if (import.meta.env.VITE_MOCK === 'true') {
      loadAllMockData().then(mockData => {
        const mockFetch = createMockFetch(mockData, API_BASE_URL);
        const originalFetch = window.fetch;
        window.fetch = async (url, opts) => {
          const mockResult = await mockFetch(url, opts);
          if (mockResult !== undefined) return mockResult;
          return originalFetch(url, opts);
        };
      });
    }
  }, []);

  const routes = buildRuntimeRoutes({ windowMap, apiBaseUrl: API_BASE_URL });

  return (
    <ObservabilityProvider
      value={{ trackMcpConnectTabSelected }}
      data-testid="ObservabilityProvider__ecaf3f">
      <AppShellRuntime
        basename={routerBase}
        menuGroups={menuGroups}
        routes={routes}
        layout={AppLayout}
        auth={{
          loginPath: '/login',
          unauthenticatedFallback: <UnauthenticatedRedirect data-testid="UnauthenticatedRedirect__ecaf3f" />,
          fetchWindowAccess,
          restoreSession,
          // ETP-4576 — with `restoreSession` wired, boot is asynchronous: AuthGate
          // renders this while `status === 'booting'`. Without it the prop defaults
          // to null and every page load flashes a blank screen until
          // GET /sws/go/session answers. Same treatment as `notFoundElement` below.
          bootingFallback: <div className="p-8 text-muted-foreground">Loading...</div>,
        }}
        locale={renderedLocale}
        setLocale={setLocale}
        dictionaries={dictionaries}
        notFoundElement={<div className="p-8 text-muted-foreground">Loading...</div>}
        data-testid="AppShellRuntime__ecaf3f">
        <ObservabilityRouteTracker data-testid="ObservabilityRouteTracker__ecaf3f" />
        <ServiceWorkerManager data-testid="ServiceWorkerManager__ecaf3f" />
        <AppStoreKeyWatcher data-testid="AppStoreKeyWatcher__ecaf3f" />
        <SurveyManager data-testid="SurveyManager__ecaf3f" />
      </AppShellRuntime>
    </ObservabilityProvider>
  );
}
