#!/usr/bin/env bash
# cli/sync-agents.sh
# Mirrors the Claude Code agent configuration into the tool-agnostic AGENTS.md
# layout that Codex, Cursor and Copilot read.
#
#   CLAUDE.md        ->  AGENTS.md
#   .claude/skills/  ->  .agents/skills/        (Codex; OpenCode reads .claude/ too)
#   .claude/agents/  ->  .codex/agents/*.toml   (Codex subagents)
#                    ->  .opencode/agents/*.md  (OpenCode subagents)
#
# Claude Code >= 2.1.277 falls back to AGENTS.md only when CLAUDE.md is absent,
# so while both exist CLAUDE.md is the file Claude actually reads and the
# mirrors are what every other agent reads. A drifted mirror hands those agents
# stale rules with no visible failure, which is exactly what happened to
# .agents/skills/ (6 of 18 skills, 3 of them outdated, unnoticed since July).
#
# Subagents are the one layer with no shared standard: Claude uses Markdown +
# YAML frontmatter, Codex uses TOML, OpenCode uses Markdown with a different
# schema. They are therefore GENERATED, not copied, and every field that
# cannot cross over is recorded in the generated file itself.
#
# OpenCode needs nothing for instructions or skills: it reads AGENTS.md with
# CLAUDE.md as a native fallback, and scans .claude/skills/ and .agents/skills/
# alongside its own path. The .agents/skills/ mirror exists for Codex.
#
# Usage:
#   ./cli/sync-agents.sh           # write the mirrors
#   ./cli/sync-agents.sh --check   # exit 1 if the mirrors are stale (CI)
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_DIR"

CHECK_ONLY=0
[ "${1:-}" = "--check" ] && CHECK_ONLY=1

STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

# --- AGENTS.md ---------------------------------------------------------------
{
  cat <<'HEADER'
<!-- GENERATED MIRROR - DO NOT EDIT THIS FILE.
     Source:     CLAUDE.md
     Regenerate: make sync-agents

     Claude Code reads CLAUDE.md. Codex, Cursor and Copilot read AGENTS.md.
     Any edit made here is lost on the next sync - edit CLAUDE.md instead.

     Transitional: when CLAUDE.md is retired, AGENTS.md becomes the real source
     and sync-agents drops this step. The script itself stays - it still
     mirrors .claude/skills/ to .agents/skills/.
-->

HEADER
  cat CLAUDE.md
} > "$STAGE/AGENTS.md"

# --- .agents/skills/ ---------------------------------------------------------
mkdir -p "$STAGE/skills"
rsync -a --delete "$REPO_DIR/.claude/skills/" "$STAGE/skills/"

# The header goes AFTER the YAML frontmatter: Codex requires the frontmatter to
# be the first thing in the file.
find "$STAGE/skills" -name SKILL.md -print0 | while IFS= read -r -d '' f; do
  rel="${f#"$STAGE/skills/"}"
  python3 - "$f" ".claude/skills/$rel" <<'PY'
import sys, pathlib
dst, src = pathlib.Path(sys.argv[1]), sys.argv[2]
text = dst.read_text()
note = (
    "<!-- GENERATED MIRROR - DO NOT EDIT. "
    f"Source: {src} - Regenerate: make sync-agents -->\n"
)
lines = text.splitlines(keepends=True)
if lines and lines[0].strip() == "---":
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            lines.insert(i + 1, "\n" + note)
            break
    else:
        lines.insert(0, note + "\n")
else:
    lines.insert(0, note + "\n")
dst.write_text("".join(lines))
PY
done

# --- subagents: .codex/agents/*.toml + .opencode/agents/*.md -----------------
N_AGENTS="$("$SCRIPT_DIR/lib-gen-agents.py" \
  "$REPO_DIR/.claude/agents" "$STAGE/codex-agents" "$STAGE/opencode-agents")"

# --- apply or verify ---------------------------------------------------------
if [ "$CHECK_ONLY" -eq 1 ]; then
  STALE=0
  cmp -s "$STAGE/AGENTS.md" "$REPO_DIR/AGENTS.md" || { echo "stale: AGENTS.md"; STALE=1; }
  for pair in "skills:.agents/skills" "codex-agents:.codex/agents" "opencode-agents:.opencode/agents"; do
    from="$STAGE/${pair%%:*}"; to="$REPO_DIR/${pair#*:}"
    if ! diff -rq "$from" "$to" >/dev/null 2>&1; then
      diff -rq "$from" "$to" 2>&1 | sed 's/^/stale: /'
      STALE=1
    fi
  done
  if [ "$STALE" -eq 1 ]; then
    echo ""
    echo "Agent mirrors are out of date. Run: make sync-agents"
    exit 1
  fi
  echo "Agent mirrors are up to date."
  exit 0
fi

cp "$STAGE/AGENTS.md" "$REPO_DIR/AGENTS.md"
mkdir -p "$REPO_DIR/.agents" "$REPO_DIR/.codex" "$REPO_DIR/.opencode"
rsync -a --delete "$STAGE/skills/"           "$REPO_DIR/.agents/skills/"
rsync -a --delete "$STAGE/codex-agents/"     "$REPO_DIR/.codex/agents/"
rsync -a --delete "$STAGE/opencode-agents/"  "$REPO_DIR/.opencode/agents/"

N_SKILLS="$(find "$REPO_DIR/.agents/skills" -name SKILL.md | wc -l | tr -d ' ')"
echo "Synced:"
echo "  AGENTS.md           <- CLAUDE.md"
echo "  .agents/skills/     <- .claude/skills/   ($N_SKILLS skills, for Codex)"
echo "  .codex/agents/      <- .claude/agents/   ($N_AGENTS subagents, TOML)"
echo "  .opencode/agents/   <- .claude/agents/   ($N_AGENTS subagents, Markdown)"
echo ""
echo "OpenCode needs no mirror for instructions or skills - it reads CLAUDE.md"
echo "and .claude/skills/ natively."
