/**
 * ETP-4656 — direct unit coverage for the shared batch-delete core
 * (`runBatchDelete` / `toastBatchDeleteOutcome`), extracted out of
 * `useBulkRowDelete.jsx` once Financial Accounts / Movements / Statements /
 * Contacts secondary tabs / DetailView's primary+secondary line deletes all
 * needed the same "Promise.allSettled triage + single-toast-per-outcome"
 * logic. Previously only exercised transitively via consumers.
 */
vi.mock('sonner', () => ({
  toast: { success: vi.fn(), warning: vi.fn(), error: vi.fn() },
}));

import { toast } from 'sonner';
import { runBatchDelete, toastBatchDeleteOutcome } from '../batchDelete.js';

/**
 * Identity-with-params for every UI key, EXCEPT the `backendError.*` namespace: `translateBackendError`
 * reads "t() returned the key" as a MISSING translation and falls back to the raw English message, so
 * a pure identity mock could never tell a translated reason from an untranslated one (ETP-5085 — same
 * trick as MovementRowKebab.lifecycle.vitest.jsx). No existing assertion below feeds a `backendError.*`
 * key, so the extra branch is inert for the pre-ETP-5085 cases.
 */
function interpolatingUi() {
  return (key, params) => {
    if (key.startsWith('backendError.')) return `translated:${key}`;
    return params ? `${key}:${JSON.stringify(params)}` : key;
  };
}

/** Builds a rejection shaped like the ones `useCreateMovement.postAction` throws: message + `status`. */
function rejectionWith(message, status) {
  const err = new Error(message);
  if (status !== undefined) err.status = status;
  return err;
}

/** A stated business reason: a 4xx whose message is a full sentence the user can act on. */
const BUSINESS_REASON = 'This movement is linked to a payment and cannot be deleted.';
const OTHER_BUSINESS_REASON = 'This movement belongs to a closed period.';
/** Present in BACKEND_ERROR_MAP -> `backendError.transferMovementNotDeletable`. */
const MAPPED_REASON = 'Movements generated by a funds transfer cannot be deleted.';

beforeEach(() => {
  vi.clearAllMocks();
});

describe('runBatchDelete', () => {
  it('all succeed: every item lands in succeeded, in input order, failed is empty', async () => {
    const items = [{ id: 'a' }, { id: 'b' }, { id: 'c' }];
    const deleteOneFn = vi.fn(async (item) => item);

    const { succeeded, failed } = await runBatchDelete(items, deleteOneFn);

    expect(succeeded).toEqual(items);
    expect(failed).toEqual([]);
    expect(deleteOneFn).toHaveBeenCalledTimes(3);
  });

  it('all fail: every item lands in failed, in input order, succeeded is empty', async () => {
    const items = [{ id: 'a' }, { id: 'b' }];
    const deleteOneFn = vi.fn(async () => { throw new Error('boom'); });

    const { succeeded, failed } = await runBatchDelete(items, deleteOneFn);

    expect(succeeded).toEqual([]);
    expect(failed).toEqual(items);
  });

  it('mixed: partitions correctly by outcome, not by call order', async () => {
    const items = [{ id: 'a' }, { id: 'b' }, { id: 'c' }];
    const deleteOneFn = vi.fn(async (item) => {
      if (item.id === 'b') throw new Error('boom');
      return item;
    });

    const { succeeded, failed } = await runBatchDelete(items, deleteOneFn);

    expect(succeeded).toEqual([{ id: 'a' }, { id: 'c' }]);
    expect(failed).toEqual([{ id: 'b' }]);
  });

  it('preserves input order in the succeeded/failed partition even when requests settle out of order', async () => {
    // 'a' is deliberately the slowest to resolve — Promise.allSettled must
    // still map each outcome back to the correct original item by index, not
    // by resolution order (mirrors useBulkRowDelete.vitest.jsx's equivalent
    // regression test for the pre-extraction inline logic).
    const items = [{ id: 'a' }, { id: 'b' }, { id: 'c' }];
    const deleteOneFn = vi.fn((item) => {
      if (item.id === 'a') {
        return Promise.resolve().then(() => Promise.resolve()).then(() => {
          throw new Error('slow failure');
        });
      }
      return Promise.resolve(item);
    });

    const { succeeded, failed } = await runBatchDelete(items, deleteOneFn);

    expect(succeeded).toEqual([{ id: 'b' }, { id: 'c' }]);
    expect(failed).toEqual([{ id: 'a' }]);
  });

  it('empty input: resolves with two empty arrays, deleteOneFn never called', async () => {
    const deleteOneFn = vi.fn();

    const { succeeded, failed } = await runBatchDelete([], deleteOneFn);

    expect(succeeded).toEqual([]);
    expect(failed).toEqual([]);
    expect(deleteOneFn).not.toHaveBeenCalled();
  });

  // ETP-5085 — `errors` is the third, purely additive return value: without it the outcome toast can
  // only ever count failures, never say why.
  it('all succeed: errors is empty (nothing to explain)', async () => {
    const items = [{ id: 'a' }, { id: 'b' }];

    const { errors } = await runBatchDelete(items, async (item) => item);

    expect(errors).toEqual([]);
  });

  it('mixed: errors carries each rejection reason, aligned by index with failed', async () => {
    const items = [{ id: 'a' }, { id: 'b' }, { id: 'c' }, { id: 'd' }];
    const bFailure = rejectionWith(BUSINESS_REASON, 409);
    const dFailure = rejectionWith(OTHER_BUSINESS_REASON, 409);
    const deleteOneFn = vi.fn(async (item) => {
      if (item.id === 'b') throw bFailure;
      if (item.id === 'd') throw dFailure;
      return item;
    });

    const { succeeded, failed, errors } = await runBatchDelete(items, deleteOneFn);

    expect(succeeded).toEqual([{ id: 'a' }, { id: 'c' }]);
    expect(failed).toEqual([{ id: 'b' }, { id: 'd' }]);
    // Same length and same order as `failed` — errors[i] explains failed[i].
    expect(errors).toHaveLength(failed.length);
    expect(errors[0]).toBe(bFailure);
    expect(errors[1]).toBe(dFailure);
  });

  it('errors stays aligned with failed even when requests settle out of order', async () => {
    // 'a' rejects last in wall-clock terms but must still be errors[0], since 'a' is failed[0].
    const items = [{ id: 'a' }, { id: 'b' }, { id: 'c' }];
    const slowFailure = rejectionWith('slow failure', 409);
    const fastFailure = rejectionWith('fast failure', 409);
    const deleteOneFn = vi.fn((item) => {
      if (item.id === 'a') {
        return Promise.resolve().then(() => Promise.resolve()).then(() => { throw slowFailure; });
      }
      if (item.id === 'c') return Promise.reject(fastFailure);
      return Promise.resolve(item);
    });

    const { failed, errors } = await runBatchDelete(items, deleteOneFn);

    expect(failed).toEqual([{ id: 'a' }, { id: 'c' }]);
    expect(errors).toEqual([slowFailure, fastFailure]);
  });
});

describe('toastBatchDeleteOutcome', () => {
  it('all succeeded (failed.length === 0): fires ONE success toast with the succeeded count', () => {
    const ui = interpolatingUi();
    toastBatchDeleteOutcome(ui, { succeeded: [{ id: 'a' }, { id: 'b' }], failed: [], total: 2 });

    expect(toast.success).toHaveBeenCalledWith('bulkDeleteAllSucceeded:{"count":2}');
    expect(toast.warning).not.toHaveBeenCalled();
    expect(toast.error).not.toHaveBeenCalled();
  });

  it('all failed (succeeded.length === 0): fires ONE error toast with the total attempted count', () => {
    const ui = interpolatingUi();
    toastBatchDeleteOutcome(ui, { succeeded: [], failed: [{ id: 'a' }, { id: 'b' }, { id: 'c' }], total: 3 });

    expect(toast.error).toHaveBeenCalledWith('bulkDeleteAllFailed:{"count":3}');
    expect(toast.success).not.toHaveBeenCalled();
    expect(toast.warning).not.toHaveBeenCalled();
  });

  it('partial failure: fires exactly ONE combined warning toast (not stacked success+error)', () => {
    const ui = interpolatingUi();
    toastBatchDeleteOutcome(ui, { succeeded: [{ id: 'a' }], failed: [{ id: 'b' }, { id: 'c' }], total: 3 });

    expect(toast.warning).toHaveBeenCalledWith(
      'bulkDeletePartialFailure:{"succeeded":1,"total":3,"failed":2}',
    );
    expect(toast.success).not.toHaveBeenCalled();
    expect(toast.error).not.toHaveBeenCalled();
  });

  it('empty batch (nothing attempted): treated as the all-succeeded branch (0 succeeded, 0 failed)', () => {
    const ui = interpolatingUi();
    toastBatchDeleteOutcome(ui, { succeeded: [], failed: [], total: 0 });

    expect(toast.success).toHaveBeenCalledWith('bulkDeleteAllSucceeded:{"count":0}');
    expect(toast.warning).not.toHaveBeenCalled();
    expect(toast.error).not.toHaveBeenCalled();
  });
});

/**
 * ETP-5085 — the failure toasts used to be counters only ("None of the 1 selected record(s) could be
 * deleted."), which told a user who bulk-deleted one undeletable funds-transfer leg nothing at all.
 * The reason is now named WHEN, and only when, every failure is a 4xx sharing one intelligible
 * message; anything else (a 500, a JS `TypeError`, a bare status code, several different reasons)
 * must keep the old counter-only wording rather than leak plumbing at the user.
 */
describe('toastBatchDeleteOutcome — common failure reason', () => {
  it('all failed, ONE item, 4xx with a message: the toast IS the backend sentence, with no counter', () => {
    const ui = interpolatingUi();
    toastBatchDeleteOutcome(ui, {
      succeeded: [],
      failed: [{ id: 'a' }],
      total: 1,
      errors: [rejectionWith(BUSINESS_REASON, 409)],
    });

    // Exactly the message: no ui() key, no interpolation, no "none of the 1 selected".
    expect(toast.error).toHaveBeenCalledWith(BUSINESS_REASON);
    expect(toast.error).not.toHaveBeenCalledWith(expect.stringContaining('bulkDelete'));
    expect(toast.success).not.toHaveBeenCalled();
    expect(toast.warning).not.toHaveBeenCalled();
  });

  it('all failed, several items sharing one 4xx reason: counter message + reason', () => {
    const ui = interpolatingUi();
    const errors = [
      rejectionWith(BUSINESS_REASON, 409),
      rejectionWith(BUSINESS_REASON, 409),
      rejectionWith(BUSINESS_REASON, 400),
    ];
    toastBatchDeleteOutcome(ui, {
      succeeded: [],
      failed: [{ id: 'a' }, { id: 'b' }, { id: 'c' }],
      total: 3,
      errors,
    });

    expect(toast.error).toHaveBeenCalledWith(
      `bulkDeleteAllFailedWithReason:{"count":3,"reason":"${BUSINESS_REASON}"}`,
    );
  });

  it('all failed for DIFFERENT 4xx reasons: falls back to the plain counter message', () => {
    const ui = interpolatingUi();
    toastBatchDeleteOutcome(ui, {
      succeeded: [],
      failed: [{ id: 'a' }, { id: 'b' }],
      total: 2,
      errors: [rejectionWith(BUSINESS_REASON, 409), rejectionWith(OTHER_BUSINESS_REASON, 409)],
    });

    // One arbitrary failure must never be presented as if it explained all of them.
    expect(toast.error).toHaveBeenCalledWith('bulkDeleteAllFailed:{"count":2}');
    expect(toast.error).not.toHaveBeenCalledWith(expect.stringContaining(BUSINESS_REASON));
  });

  it('errors carrying no status (a plain JS Error): plain counter message, never the raw text', () => {
    // The guard that stops `deleteOneFn` bugs and network failures from being shown as if the
    // backend had refused for a reason.
    const ui = interpolatingUi();
    toastBatchDeleteOutcome(ui, {
      succeeded: [],
      failed: [{ id: 'a' }, { id: 'b' }],
      total: 2,
      errors: [new Error('boom'), new Error('boom')],
    });

    expect(toast.error).toHaveBeenCalledWith('bulkDeleteAllFailed:{"count":2}');
    expect(toast.error).not.toHaveBeenCalledWith(expect.stringContaining('boom'));
  });

  it('a 5xx is not a stated reason: plain counter message', () => {
    const ui = interpolatingUi();
    toastBatchDeleteOutcome(ui, {
      succeeded: [],
      failed: [{ id: 'a' }],
      total: 1,
      errors: [rejectionWith('Internal error. Please check logs for details.', 500)],
    });

    expect(toast.error).toHaveBeenCalledWith('bulkDeleteAllFailed:{"count":1}');
    expect(toast.error).not.toHaveBeenCalledWith(expect.stringContaining('check logs'));
  });

  it('one non-4xx failure in an otherwise-explained batch suppresses the reason for all', () => {
    const ui = interpolatingUi();
    toastBatchDeleteOutcome(ui, {
      succeeded: [],
      failed: [{ id: 'a' }, { id: 'b' }],
      total: 2,
      errors: [rejectionWith(BUSINESS_REASON, 409), rejectionWith('Gateway timeout', 504)],
    });

    expect(toast.error).toHaveBeenCalledWith('bulkDeleteAllFailed:{"count":2}');
  });

  it.each(['HTTP 409', '409 Conflict', 'HTTP 400: {"error":{"message":"x"}}'])(
    'an opaque 4xx message (%s) is not a reason: plain counter message',
    (opaque) => {
      const ui = interpolatingUi();
      toastBatchDeleteOutcome(ui, {
        succeeded: [],
        failed: [{ id: 'a' }],
        total: 1,
        errors: [rejectionWith(opaque, 409)],
      });

      expect(toast.error).toHaveBeenCalledWith('bulkDeleteAllFailed:{"count":1}');
      expect(toast.error).not.toHaveBeenCalledWith(opaque);
    },
  );

  it('a 4xx with a blank message is not a reason: plain counter message', () => {
    const ui = interpolatingUi();
    toastBatchDeleteOutcome(ui, {
      succeeded: [],
      failed: [{ id: 'a' }],
      total: 1,
      errors: [rejectionWith('   ', 409)],
    });

    expect(toast.error).toHaveBeenCalledWith('bulkDeleteAllFailed:{"count":1}');
  });

  it('a caller that never passes errors keeps the old wording (the change is additive)', () => {
    const ui = interpolatingUi();
    toastBatchDeleteOutcome(ui, { succeeded: [], failed: [{ id: 'a' }], total: 1 });

    expect(toast.error).toHaveBeenCalledWith('bulkDeleteAllFailed:{"count":1}');
  });

  it('partial failure sharing one 4xx reason: warning toast names it alongside the counts', () => {
    const ui = interpolatingUi();
    toastBatchDeleteOutcome(ui, {
      succeeded: [{ id: 'a' }],
      failed: [{ id: 'b' }, { id: 'c' }],
      total: 3,
      errors: [rejectionWith(BUSINESS_REASON, 409), rejectionWith(BUSINESS_REASON, 409)],
    });

    expect(toast.warning).toHaveBeenCalledWith(
      `bulkDeletePartialFailureWithReason:{"succeeded":1,"total":3,"failed":2,"reason":"${BUSINESS_REASON}"}`,
    );
    expect(toast.success).not.toHaveBeenCalled();
    expect(toast.error).not.toHaveBeenCalled();
  });

  it('partial failure without a common reason: the pre-ETP-5085 warning toast, unchanged', () => {
    const ui = interpolatingUi();
    toastBatchDeleteOutcome(ui, {
      succeeded: [{ id: 'a' }],
      failed: [{ id: 'b' }, { id: 'c' }],
      total: 3,
      errors: [new Error('boom'), rejectionWith(BUSINESS_REASON, 409)],
    });

    expect(toast.warning).toHaveBeenCalledWith(
      'bulkDeletePartialFailure:{"succeeded":1,"total":3,"failed":2}',
    );
  });

  it('all succeeded: errors are irrelevant, the success toast still fires', () => {
    const ui = interpolatingUi();
    toastBatchDeleteOutcome(ui, { succeeded: [{ id: 'a' }], failed: [], total: 1, errors: [] });

    expect(toast.success).toHaveBeenCalledWith('bulkDeleteAllSucceeded:{"count":1}');
    expect(toast.error).not.toHaveBeenCalled();
  });

  it('the reason goes through translateBackendError: a mapped message is shown translated', () => {
    // The original ETP-5085 complaint — deleting one leg of a funds transfer.
    const ui = interpolatingUi();
    toastBatchDeleteOutcome(ui, {
      succeeded: [],
      failed: [{ id: 'a' }],
      total: 1,
      errors: [rejectionWith(MAPPED_REASON, 409)],
    });

    expect(toast.error).toHaveBeenCalledWith('translated:backendError.transferMovementNotDeletable');
    expect(toast.error).not.toHaveBeenCalledWith(MAPPED_REASON);
  });

  it('translation happens before dedup: same mapped message across items is still one reason', () => {
    const ui = interpolatingUi();
    toastBatchDeleteOutcome(ui, {
      succeeded: [],
      failed: [{ id: 'a' }, { id: 'b' }],
      total: 2,
      errors: [rejectionWith(MAPPED_REASON, 409), rejectionWith(MAPPED_REASON, 409)],
    });

    expect(toast.error).toHaveBeenCalledWith(
      'bulkDeleteAllFailedWithReason:{"count":2,"reason":"translated:backendError.transferMovementNotDeletable"}',
    );
  });
});
