// Unit tests for the G/L-transaction lifecycle actions added to the movement
// row kebab (ETP-4500): Confirmar / Reactivar / Eliminar. These are shown ONLY
// for manual G/L transactions (no `paymentId`); the visibility matrix and each
// action's hook call + toast + onReload wiring are verified here. The existing
// MovementRowKebab.vitest.jsx (Post action) is left untouched.

// Identity for every UI label, EXCEPT the backendError.* namespace: `translateBackendError` reads
// "t() returned the key" as a MISSING translation and falls back to the raw English, so a pure
// identity mock could never tell a translated toast from an untranslated one (ETP-5085).
vi.mock('@/i18n', () => ({
  useUI: () => (key) => (key.startsWith('backendError.') ? `translated:${key}` : key),
}));

const toastSuccess = vi.fn();
const toastError = vi.fn();
vi.mock('sonner', () => ({
  toast: { success: (...a) => toastSuccess(...a), error: (...a) => toastError(...a) },
}));

vi.mock('@/auth/AuthContext.jsx', () => ({
  useAuth: () => ({ token: 'test-token' }),
}));

vi.mock('@/hooks/useNeoResource', () => ({
  getApiBase: () => '',
}));

// The three lifecycle hooks are the side effects under test — shared spies.
const processMovement = vi.fn();
const reactivateMovement = vi.fn();
const deleteMovement = vi.fn();
const postMovement = vi.fn();
vi.mock('@/hooks/useCreateMovement', () => ({
  useProcessMovement: () => ({ processMovement, processing: false }),
  useReactivateMovement: () => ({ reactivateMovement, reactivating: false }),
  useDeleteMovement: () => ({ deleteMovement, deleting: false }),
  usePostMovement: () => ({ postMovement, posting: false }),
}));

vi.mock('lucide-react', () => ({
  MoreVertical: () => null,
  ExternalLink: () => null,
  GitMerge: () => null,
  BookOpen: () => null,
  BookX: () => null,
  CheckCircle2: () => null,
  RotateCcw: () => null,
  Trash2: () => null,
  Pencil: () => null,
}));

vi.mock('@/components/ui/dropdown-menu', () => ({
  DropdownMenu: ({ children }) => <div>{children}</div>,
  DropdownMenuTrigger: ({ children }) => <div>{children}</div>,
  DropdownMenuContent: ({ children }) => <div>{children}</div>,
  DropdownMenuItem: ({ children, onClick, disabled, 'data-testid': dtid, ...rest }) => (
    <button
      role="menuitem"
      onClick={disabled ? undefined : onClick}
      aria-disabled={disabled ? 'true' : undefined}
      data-testid={dtid}
      {...rest}
    >
      {children}
    </button>
  ),
  DropdownMenuSeparator: () => <hr />,
}));

vi.mock('@/components/ui/tooltip', () => ({
  TooltipProvider: ({ children }) => <div>{children}</div>,
  Tooltip: ({ children }) => <div>{children}</div>,
  TooltipTrigger: ({ children }) => <div>{children}</div>,
  TooltipContent: ({ children }) => <div>{children}</div>,
}));

import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MovementRowKebab } from '../MovementRowKebab.jsx';

// GL draft: no paymentId, not processed → Confirmar + Eliminar.
const GL_DRAFT = { id: 'gl-draft', posted: 'N', processed: false };
// GL processed: no paymentId, processed → Reactivar + Eliminar.
const GL_PROCESSED = { id: 'gl-proc', posted: 'Y', processed: true };
// Payment-linked: has paymentId → none of the three lifecycle actions.
const PAYMENT_LINKED = { id: 'pay-1', posted: 'Y', processed: true, paymentId: 'p-1' };

// ETP-5085. The two legs of a funds transfer reference each other through RESTRICT self-FKs on
// FIN_FINACC_TRANSACTION, so deleting either one could only ever fail — and it failed at flush
// time as an opaque HTTP 500. Eliminar is now hidden for those rows (the backend also rejects them
// with a 409). Row shape mirrors what the backend sends the table: see the counterpart-link suite
// in MovementsTable.vitest.jsx.
const TRANSFER_LEG = {
  id: 'trf-out',
  posted: 'N',
  processed: true,
  trxType: 'BPW',
  transferTxnId: 'txn-2',
  transferAccountId: 'acct-far',
  transferAccountName: 'Banco Santander',
  transferDirection: 'out',
};
// A bank fee carries the SAME transferTxnId as a leg, yet nothing references IT — the gate is the
// FK direction, not the mere presence of a transfer link — so it stays deletable.
const TRANSFER_BANK_FEE = { ...TRANSFER_LEG, id: 'trf-fee', trxType: 'BF', processed: false };

const TRANSFER_NOT_DELETABLE = 'Movements generated by a funds transfer cannot be deleted.';

function renderKebab(movement, onEdit = vi.fn()) {
  const onReload = vi.fn();
  render(<MovementRowKebab movement={movement} onReload={onReload} onEdit={onEdit} />);
  return { onReload, onEdit };
}

beforeEach(() => {
  processMovement.mockReset().mockResolvedValue({});
  reactivateMovement.mockReset().mockResolvedValue({});
  deleteMovement.mockReset().mockResolvedValue({});
  toastSuccess.mockClear();
  toastError.mockClear();
});

describe('MovementRowKebab — lifecycle visibility matrix', () => {
  it('GL draft shows Editar + Procesar + Eliminar, hides Reactivar', () => {
    renderKebab(GL_DRAFT);
    expect(screen.getByTestId('movement-row-edit')).toBeInTheDocument();
    expect(screen.getByTestId('movement-row-process')).toBeInTheDocument();
    expect(screen.getByTestId('movement-row-delete')).toBeInTheDocument();
    expect(screen.queryByTestId('movement-row-reactivate')).not.toBeInTheDocument();
  });

  it('GL processed shows Reactivar + Eliminar, hides Editar + Procesar', () => {
    renderKebab(GL_PROCESSED);
    expect(screen.getByTestId('movement-row-reactivate')).toBeInTheDocument();
    expect(screen.getByTestId('movement-row-delete')).toBeInTheDocument();
    expect(screen.queryByTestId('movement-row-edit')).not.toBeInTheDocument();
    expect(screen.queryByTestId('movement-row-process')).not.toBeInTheDocument();
  });

  it('processed but NOT posted still shows Editar (partial edit) + Reactivar', () => {
    renderKebab({ id: 'gl-pnp', posted: 'N', processed: true });
    expect(screen.getByTestId('movement-row-edit')).toBeInTheDocument();
    expect(screen.getByTestId('movement-row-reactivate')).toBeInTheDocument();
    // Confirmar (Draft → Processed) is gone — it's already processed.
    expect(screen.queryByTestId('movement-row-process')).not.toBeInTheDocument();
  });

  it('payment-linked, posted movement exposes only Unpost (no G/L lifecycle actions)', () => {
    renderKebab(PAYMENT_LINKED);
    // All G/L-only actions are hidden — this movement is managed from the Payments module.
    expect(screen.queryByTestId('movement-row-edit')).not.toBeInTheDocument();
    expect(screen.queryByTestId('movement-row-process')).not.toBeInTheDocument();
    expect(screen.queryByTestId('movement-row-reactivate')).not.toBeInTheDocument();
    expect(screen.queryByTestId('movement-row-delete')).not.toBeInTheDocument();
    // But because it is posted, Unpost (descontabilizar) keeps the kebab alive (ETP-4505 merge).
    expect(screen.getByTestId(`movement-row-menu-${PAYMENT_LINKED.id}`)).toBeInTheDocument();
    expect(screen.getByTestId('movement-row-unpost')).toBeInTheDocument();
  });

  // ── funds-transfer delete guard (ETP-5085) ────────────────────────────────
  it('plain G/L movement (no transfer link) keeps Eliminar', () => {
    renderKebab(GL_DRAFT);
    expect(screen.getByTestId('movement-row-delete')).toBeInTheDocument();
  });

  it('a funds-transfer leg hides Eliminar but keeps its other applicable actions', () => {
    renderKebab(TRANSFER_LEG);
    expect(screen.queryByTestId('movement-row-delete')).not.toBeInTheDocument();
    // Hiding one item must not collapse the kebab or drop what a leg legitimately still supports:
    // processed and not posted → Reactivar + Contabilizar + partial Editar.
    expect(screen.getByTestId(`movement-row-menu-${TRANSFER_LEG.id}`)).toBeInTheDocument();
    expect(screen.getByTestId('movement-row-reactivate')).toBeInTheDocument();
    expect(screen.getByTestId('movement-row-post')).toBeInTheDocument();
    expect(screen.getByTestId('movement-row-edit')).toBeInTheDocument();
  });

  it('a transfer bank fee (BF) keeps Eliminar and deletes through the hook', async () => {
    const user = userEvent.setup();
    const { onReload } = renderKebab(TRANSFER_BANK_FEE);
    expect(screen.getByTestId('movement-row-delete')).toBeInTheDocument();

    await user.click(screen.getByTestId('movement-row-delete'));
    await waitFor(() => expect(deleteMovement).toHaveBeenCalledWith({ id: 'trf-fee' }));
    expect(toastSuccess).toHaveBeenCalledWith('financeAccountTxRowDeleteSuccess');
    expect(onReload).toHaveBeenCalledOnce();
  });
});

// ETP-5085. The row-level guard only covers rows whose transfer link the list actually exposes; a
// legacy transfer (created before the mirror FK column existed) still reaches the backend and comes
// back as the 409. The hook now propagates that sentence verbatim instead of wrapping it in
// `HTTP <status>: <raw body>`, so the kebab can look it up in BACKEND_ERROR_MAP and translate it —
// what the user must never read is the English original.
describe('MovementRowKebab — backend rejection is translated', () => {
  const LEGACY_TRANSFER_LEG = { id: 'legacy-leg', posted: 'N', processed: false };

  it('shows the translated message when the backend guard rejects the delete', async () => {
    const rejection = new Error(TRANSFER_NOT_DELETABLE);
    rejection.status = 409;
    deleteMovement.mockRejectedValue(rejection);

    const user = userEvent.setup();
    const { onReload } = renderKebab(LEGACY_TRANSFER_LEG);
    await user.click(screen.getByTestId('movement-row-delete'));

    await waitFor(() => expect(toastError).toHaveBeenCalledOnce());
    expect(toastError).toHaveBeenCalledWith('translated:backendError.transferMovementNotDeletable');
    expect(toastError).not.toHaveBeenCalledWith(TRANSFER_NOT_DELETABLE);
    expect(onReload).not.toHaveBeenCalled();
    expect(toastSuccess).not.toHaveBeenCalled();
  });

  // Regression on the SHAPE of the old bug: `HTTP 500: {"error":{"message":…}}` is not a
  // BACKEND_ERROR_MAP key, so a wrapped message could only ever reach the toast raw.
  it('never receives an HTTP-status-wrapped message from the hook', async () => {
    const rejection = new Error(TRANSFER_NOT_DELETABLE);
    rejection.status = 409;
    deleteMovement.mockRejectedValue(rejection);

    const user = userEvent.setup();
    renderKebab(LEGACY_TRANSFER_LEG);
    await user.click(screen.getByTestId('movement-row-delete'));

    await waitFor(() => expect(toastError).toHaveBeenCalledOnce());
    expect(toastError.mock.calls[0][0]).not.toMatch(/HTTP \d+/);
  });
});

describe('MovementRowKebab — lifecycle actions', () => {
  it('Procesar calls processMovement with { id }, then toast.success + onReload', async () => {
    const user = userEvent.setup();
    const { onReload } = renderKebab(GL_DRAFT);
    await user.click(screen.getByTestId('movement-row-process'));

    await waitFor(() => expect(processMovement).toHaveBeenCalledWith({ id: 'gl-draft' }));
    expect(toastSuccess).toHaveBeenCalledWith('financeAccountTxRowProcessSuccess');
    expect(onReload).toHaveBeenCalledOnce();
    expect(toastError).not.toHaveBeenCalled();
  });

  it('Editar invokes onEdit with the movement (no hook call)', async () => {
    const user = userEvent.setup();
    const onEdit = vi.fn();
    renderKebab(GL_DRAFT, onEdit);
    await user.click(screen.getByTestId('movement-row-edit'));

    expect(onEdit).toHaveBeenCalledWith(GL_DRAFT);
    expect(processMovement).not.toHaveBeenCalled();
  });

  it('Reactivar opens the confirm dialog, then calls reactivateMovement on accept', async () => {
    const user = userEvent.setup();
    const { onReload } = renderKebab(GL_PROCESSED);
    await user.click(screen.getByTestId('movement-row-reactivate'));

    // A confirmation dialog is shown before running the destructive action.
    expect(screen.getByTestId('movement-confirm-modal')).toBeInTheDocument();
    expect(reactivateMovement).not.toHaveBeenCalled();

    await user.click(screen.getByTestId('movement-confirm-accept'));
    await waitFor(() => expect(reactivateMovement).toHaveBeenCalledWith({ id: 'gl-proc' }));
    expect(toastSuccess).toHaveBeenCalledWith('financeAccountTxRowReactivateSuccess');
    expect(onReload).toHaveBeenCalledOnce();
  });

  it('Eliminar on a Draft removes it directly (no confirm dialog)', async () => {
    const user = userEvent.setup();
    const { onReload } = renderKebab(GL_DRAFT);
    await user.click(screen.getByTestId('movement-row-delete'));

    expect(screen.queryByTestId('movement-confirm-modal')).not.toBeInTheDocument();
    await waitFor(() => expect(deleteMovement).toHaveBeenCalledWith({ id: 'gl-draft' }));
    expect(toastSuccess).toHaveBeenCalledWith('financeAccountTxRowDeleteSuccess');
    expect(onReload).toHaveBeenCalledOnce();
  });

  it('Eliminar on a Processed & posted movement confirms first, then calls deleteMovement', async () => {
    const user = userEvent.setup();
    // Posted (contabilizado) → there is something to undo → confirm.
    const { onReload } = renderKebab({ id: 'gl-proc2', posted: 'Y', processed: true });
    await user.click(screen.getByTestId('movement-row-delete'));

    expect(screen.getByTestId('movement-confirm-modal')).toBeInTheDocument();
    expect(deleteMovement).not.toHaveBeenCalled();

    await user.click(screen.getByTestId('movement-confirm-accept'));
    await waitFor(() => expect(deleteMovement).toHaveBeenCalledWith({ id: 'gl-proc2' }));
    expect(onReload).toHaveBeenCalledOnce();
  });

  it('Reactivar a merely-Processed (not posted/reconciled) movement runs directly, no dialog', async () => {
    const user = userEvent.setup();
    const { onReload } = renderKebab({ id: 'gl-proc3', posted: 'N', processed: true });
    await user.click(screen.getByTestId('movement-row-reactivate'));

    expect(screen.queryByTestId('movement-confirm-modal')).not.toBeInTheDocument();
    await waitFor(() => expect(reactivateMovement).toHaveBeenCalledWith({ id: 'gl-proc3' }));
    expect(onReload).toHaveBeenCalledOnce();
  });

  it('surfaces toast.error and skips onReload when the hook rejects', async () => {
    processMovement.mockRejectedValue(new Error('Cannot process'));
    const user = userEvent.setup();
    const { onReload } = renderKebab(GL_DRAFT);
    await user.click(screen.getByTestId('movement-row-process'));

    await waitFor(() => expect(toastError).toHaveBeenCalledWith('Cannot process'));
    expect(onReload).not.toHaveBeenCalled();
    expect(toastSuccess).not.toHaveBeenCalled();
  });

  it('falls back to the error label key when the rejection has no message', async () => {
    deleteMovement.mockRejectedValue(new Error(''));
    const user = userEvent.setup();
    renderKebab(GL_DRAFT);
    await user.click(screen.getByTestId('movement-row-delete'));

    await waitFor(() => expect(toastError).toHaveBeenCalledWith('financeAccountTxRowDeleteError'));
  });
});
