/**
 * ETP-5013 — remove the trailing "Generated by Etendo Go" footer from every
 * LISTING report.
 *
 * Before this change, every listing `template.hbs` closed with:
 *
 *   <div class="report-footer">
 *     <div>{{meta.ui.generatedBy}}</div>
 *   </div>
 *
 * `report-order-not-shipped/template.hbs` had the same block but with the
 * string hardcoded in English instead of going through `meta.ui.generatedBy`
 * (an i18n bug on its own, moot now that the whole block is gone).
 *
 * This test is a source/structure check (not a full render) that guards
 * against the block being reintroduced by a future template edit or a
 * `make regen` that reuses a stale template as a base.
 *
 * Print/document templates (`print-*`) are intentionally out of scope — they
 * never had `.report-footer`; they render their own `.doc-footer` with the
 * company name, which is unrelated to this change.
 */
import { describe, it } from 'node:test';
import { strict as assert } from 'node:assert';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// Same 10 listing reports covered by report-listing-templates-branding.test.js
// — kept explicit (not globbed) so a new listing report that regresses this
// doesn't silently slip through uncovered.
const LISTING_REPORTS = [
  'report-general-ledger',
  'balance-sheet',
  'profit-loss',
  'inventory-stock-report',
  'report-journal-entries',
  'report-order-not-shipped',
  'report-trial-balance',
  'aging-payable',
  'aging-receivable',
  'tax-report',
];

function readTemplate(reportId) {
  return readFileSync(
    fileURLToPath(new URL(`../../../artifacts/${reportId}/template.hbs`, import.meta.url)),
    'utf8',
  );
}

describe('listing report templates — no trailing "generated by" footer (ETP-5013)', () => {
  for (const reportId of LISTING_REPORTS) {
    it(`${reportId}/template.hbs does not contain a .report-footer block`, () => {
      const source = readTemplate(reportId);
      assert.doesNotMatch(source, /class="report-footer"/);
    });

    it(`${reportId}/template.hbs does not reference meta.ui.generatedBy`, () => {
      const source = readTemplate(reportId);
      assert.doesNotMatch(source, /meta\.ui\.generatedBy/);
    });

    it(`${reportId}/template.hbs does not hardcode a "Generated by" string`, () => {
      // report-order-not-shipped previously hardcoded the English string
      // instead of going through meta.ui.generatedBy — guard against either
      // form reappearing.
      const source = readTemplate(reportId);
      assert.doesNotMatch(source, /Generated by/i);
      assert.doesNotMatch(source, /Generado por/i);
    });
  }
});
