/**
 * ETP-4900 — bug: `aging-payable`'s and `aging-receivable`'s
 * `template-excel.hbs` / `template-csv.hbs` (byte-identical between the two
 * reports — see each file's own header comment) rendered an EXTRA row/line
 * after every contact's document rows when `meta.showDetails` is true: a
 * stray per-contact subtotal repeating the contact name with blank
 * docNo/date and the contact-level aggregate amounts (including
 * `credits`/`net`). In an otherwise one-row-per-document export this breaks
 * pivot tables / SUM() ranges built over the sheet.
 *
 * Fix: the subtotal row is gone. Since it was the ONLY place Credit/Net
 * appeared in the detail view, each DOCUMENT row now carries its own:
 *   - Credit is always the literal 0 — `AgingReportHandler.buildDocRow`
 *     (Java) never sends a per-document credit; credit is a contact-level
 *     concept only.
 *   - Net is `sumFields(current, days30, days60, days90, days120,
 *     days150plus)` (canonical helper,
 *     templates/reports/helpers/report-html-helpers.js) — the same math the
 *     PDF's per-card subtotal already showed, just computed per document.
 *
 * `round2` is a REPORT-SPECIFIC extra (aging's own helpers.js), not part of
 * the canonical set registered by `registerReportHelpers()` — production
 * renders BOTH the xlsx AND csv formats through the jsreport container (see
 * report-api.js: only `format === 'html'` takes the direct
 * `registerReportHelpers` + `Handlebars.compile` path; xlsx/csv both go
 * through `buildJsreportHelpersString`, which folds in a report's extras).
 * So both render helpers below use `buildJsreportHelpersString` + `new
 * Function`, mirroring production exactly for THIS report (unlike sibling
 * report tests whose template-excel.hbs never touches a report-specific
 * helper and can get away with `registerReportHelpers` alone).
 *
 * The summary view (`meta.showDetails: false`, one row per contact) is
 * UNCHANGED — covered here only as a quick regression check.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import Handlebars from 'handlebars';
import { buildJsreportHelpersString } from '../../../templates/reports/helpers/report-html-helpers.js';

const REPORTS = ['aging-payable', 'aging-receivable'];

const LABELS = {
  bPartner: 'Contacto',
  documentNo: 'Nº Documento',
  documentDate: 'Fecha Documento',
  current: 'Actual',
  total: 'Total',
  credits: 'Crédito',
  net: 'Neto',
};

const META_BASE = {
  title: 'Antigüedad de Saldos',
  recordCount: 2,
  ui: { records: 'registros', total: 'Total', generatedBy: 'Generated by Schema Forge' },
  labels: LABELS,
  column1: 30,
  column2: 60,
  column3: 90,
  column4: 120,
  lastBucketLabel: '+120',
};

// Two contacts, two documents each (4 documents total). Deliberately
// different bucket-amount combinations per document:
//   DOC-001 — only days30 nonzero
//   DOC-002 — only days150plus (the >120 bucket) nonzero
//   DOC-101 — current + days30 both nonzero, with decimals (rounding path)
//   DOC-102 — days120 + days150plus both nonzero
function buildDocs() {
  return [
    {
      bPartner: 'Contacto Uno',
      total: 1000, credits: 50, net: 950,
      current: 100, days30: 200, days60: 300, days90: 150, days120: 100, days150plus: 150,
      docs: [
        { docNo: 'DOC-001', dateInvoiced: '2026-08-01', current: 0, days30: 100, days60: 0, days90: 0, days120: 0, days150plus: 0 },
        { docNo: 'DOC-002', dateInvoiced: '2026-08-05', current: 0, days30: 0, days60: 0, days90: 0, days120: 0, days150plus: 50 },
      ],
    },
    {
      bPartner: 'Contacto Dos',
      total: 500, credits: 20, net: 480,
      current: 50, days30: 0, days60: 0, days90: 0, days120: 0, days150plus: 450,
      docs: [
        { docNo: 'DOC-101', dateInvoiced: '2026-08-02', current: 25.5, days30: 10.25, days60: 0, days90: 0, days120: 0, days150plus: 0 },
        { docNo: 'DOC-102', dateInvoiced: '2026-08-10', current: 0, days30: 0, days60: 0, days90: 0, days120: 30, days150plus: 20 },
      ],
    },
  ];
}

const TOTAL_DOC_COUNT = buildDocs().reduce((sum, r) => sum + r.docs.length, 0);

function loadHelpers(artifactDir) {
  const helpersPath = resolve(artifactDir, 'helpers.js');
  return readFileSync(helpersPath, 'utf8');
}

function evalHelpers(helpersCode, separators) {
  const built = buildJsreportHelpersString(helpersCode, undefined, separators);
  const helperNames = [...built.matchAll(/^function\s+(\w+)\s*\(/gm)].map((m) => m[1]);
  // eslint-disable-next-line no-new-func
  return new Function(`${built}\nreturn { ${helperNames.join(', ')} };`)();
}

function renderExcel(artifactDir, { rows, showDetails, showBucket2 = true, showBucket3 = true, showBucket4 = true } = {}) {
  const helpersCode = loadHelpers(artifactDir);
  const helpers = evalHelpers(helpersCode);
  const hb = Handlebars.create();
  for (const [name, fn] of Object.entries(helpers)) hb.registerHelper(name, fn);
  const templateSrc = readFileSync(resolve(artifactDir, 'template-excel.hbs'), 'utf8');
  const template = hb.compile(templateSrc);
  return template({
    meta: { ...META_BASE, showDetails, showBucket2, showBucket3, showBucket4 },
    rows,
  });
}

function renderCsv(artifactDir, { rows, showDetails, showBucket2 = true, showBucket3 = true, showBucket4 = true } = {}) {
  const helpersCode = loadHelpers(artifactDir);
  const helpers = evalHelpers(helpersCode);
  const hb = Handlebars.create();
  for (const [name, fn] of Object.entries(helpers)) hb.registerHelper(name, fn);
  const templateSrc = readFileSync(resolve(artifactDir, 'template-csv.hbs'), 'utf8');
  const template = hb.compile(templateSrc);
  return template({
    meta: { ...META_BASE, showDetails, showBucket2, showBucket3, showBucket4 },
    rows,
  });
}

function countTbodyRows(html) {
  const bodyMatch = html.match(/<tbody>([\s\S]*?)<\/tbody>/);
  assert.ok(bodyMatch, 'expected a <tbody> in the rendered Excel HTML');
  return (bodyMatch[1].match(/<tr>/g) || []).length;
}

function extractRow(html, marker) {
  const idx = html.indexOf(marker);
  assert.ok(idx !== -1, `expected to find "${marker}" in the rendered output`);
  const start = html.lastIndexOf('<tr>', idx);
  const end = html.indexOf('</tr>', idx);
  return html.slice(start, end);
}

function cellsOf(row) {
  return [...row.matchAll(/<td[^>]*>([^<]*)<\/td>/g)].map((m) => m[1]);
}

for (const reportId of REPORTS) {
  const artifactDir = resolve(import.meta.dirname, '../../../artifacts', reportId);

  describe(`${reportId} — template-excel.hbs (Detail view, ETP-4900)`, () => {
    it('renders EXACTLY one <tr> per document — no extra per-contact subtotal row', () => {
      const html = renderExcel(artifactDir, { rows: buildDocs(), showDetails: true });
      assert.equal(countTbodyRows(html), TOTAL_DOC_COUNT);
    });

    it('never renders the old subtotal-row shape (blank docNo/date cells)', () => {
      const html = renderExcel(artifactDir, { rows: buildDocs(), showDetails: true });
      // Old shape: <td>{{../bPartner}}</td><td></td><td></td>... — a row whose
      // 2nd and 3rd <td> are both empty. No document row can produce this
      // (docNo/dateInvoiced are always populated in real data).
      assert.doesNotMatch(html, /<td>[^<]*<\/td>\s*<td><\/td>\s*<td><\/td>/);
    });

    it('DOC-001 (only days30 nonzero): Credit is literal 0, Net = sum of its own bucket amounts', () => {
      const html = renderExcel(artifactDir, { rows: buildDocs(), showDetails: true });
      const row = extractRow(html, 'DOC-001');
      const cells = cellsOf(row);
      const credit = cells[cells.length - 2];
      const net = cells[cells.length - 1];
      assert.equal(credit, '0');
      // current 0 + days30 100 + days60 0 + days90 0 + days120 0 + days150plus 0
      assert.equal(Number(net), 100);
    });

    it('DOC-002 (only days150plus/>120 nonzero): Credit is literal 0, Net = sum of its own bucket amounts', () => {
      const html = renderExcel(artifactDir, { rows: buildDocs(), showDetails: true });
      const row = extractRow(html, 'DOC-002');
      const cells = cellsOf(row);
      const credit = cells[cells.length - 2];
      const net = cells[cells.length - 1];
      assert.equal(credit, '0');
      // current 0 + days30 0 + days60 0 + days90 0 + days120 0 + days150plus 50
      assert.equal(Number(net), 50);
    });

    it('DOC-101 (decimal amounts, current+days30): Net sums correctly with rounding applied', () => {
      const html = renderExcel(artifactDir, { rows: buildDocs(), showDetails: true });
      const row = extractRow(html, 'DOC-101');
      const cells = cellsOf(row);
      const credit = cells[cells.length - 2];
      const net = cells[cells.length - 1];
      assert.equal(credit, '0');
      // 25.5 + 10.25 = 35.75, already <= 2 decimals — round2 is a no-op here
      assert.equal(Number(net), 35.75);
    });

    it('works correctly when only SOME buckets are visually active — sumFields always sums all 6 fields', () => {
      const html = renderExcel(artifactDir, {
        rows: buildDocs(),
        showDetails: true,
        showBucket2: true,
        showBucket3: false,
        showBucket4: false,
      });
      // Still exactly one row per doc even with fewer columns rendered.
      assert.equal(countTbodyRows(html), TOTAL_DOC_COUNT);
      const row = extractRow(html, 'DOC-102');
      const cells = cellsOf(row);
      const credit = cells[cells.length - 2];
      const net = cells[cells.length - 1];
      assert.equal(credit, '0');
      // days120 30 + days150plus 20 = 50, regardless of showBucket4 being off
      // (days120's amount already reflects the visible-bucket collapsing done
      // upstream in Java — sumFields must still fold it into the total here).
      assert.equal(Number(net), 50);
    });
  });

  describe(`${reportId} — template-csv.hbs (Detail view, ETP-4900)`, () => {
    function dataLines(csv) {
      // First line is the header; every subsequent non-empty line is a data row.
      return csv.split('\n').filter((l) => l.trim() !== '').slice(1);
    }

    it('renders EXACTLY one line per document — no extra per-contact subtotal line', () => {
      const csv = renderCsv(artifactDir, { rows: buildDocs(), showDetails: true });
      assert.equal(dataLines(csv).length, TOTAL_DOC_COUNT);
    });

    it('DOC-001 and DOC-002 trailing fields (Credit, Net) match the Excel math', () => {
      const csv = renderCsv(artifactDir, { rows: buildDocs(), showDetails: true });
      const lines = dataLines(csv);
      const doc001 = lines.find((l) => l.includes('DOC-001'));
      const doc002 = lines.find((l) => l.includes('DOC-002'));
      assert.ok(doc001 && doc002);
      const fields001 = doc001.split(',');
      const fields002 = doc002.split(',');
      assert.equal(fields001[fields001.length - 2], '0');
      assert.equal(Number(fields001[fields001.length - 1]), 100);
      assert.equal(fields002[fields002.length - 2], '0');
      assert.equal(Number(fields002[fields002.length - 1]), 50);
    });

    it('DOC-101 trailing fields reflect the decimal sum (Credit 0, Net 35.75)', () => {
      const csv = renderCsv(artifactDir, { rows: buildDocs(), showDetails: true });
      const lines = dataLines(csv);
      const doc101 = lines.find((l) => l.includes('DOC-101'));
      assert.ok(doc101);
      const fields = doc101.split(',');
      assert.equal(fields[fields.length - 2], '0');
      assert.equal(Number(fields[fields.length - 1]), 35.75);
    });

    it('works correctly when only SOME buckets are visually active', () => {
      const csv = renderCsv(artifactDir, {
        rows: buildDocs(),
        showDetails: true,
        showBucket2: true,
        showBucket3: false,
        showBucket4: false,
      });
      const lines = dataLines(csv);
      assert.equal(lines.length, TOTAL_DOC_COUNT);
      const doc102 = lines.find((l) => l.includes('DOC-102'));
      assert.ok(doc102);
      const fields = doc102.split(',');
      assert.equal(fields[fields.length - 2], '0');
      assert.equal(Number(fields[fields.length - 1]), 50);
    });
  });

  describe(`${reportId} — Summary view (meta.showDetails=false) — regression, unchanged`, () => {
    const SUMMARY_ROWS = [
      { bPartner: 'Contacto Uno', current: 100, days30: 200, days60: 300, days90: 150, days120: 100, days150plus: 150, total: 1000, credits: 50, net: 950 },
      { bPartner: 'Contacto Dos', current: 50, days30: 0, days60: 0, days90: 0, days120: 0, days150plus: 450, total: 500, credits: 20, net: 480 },
    ];

    it('Excel: one row per contact, using the row own aggregate total/credits/net', () => {
      const html = renderExcel(artifactDir, { rows: SUMMARY_ROWS, showDetails: false });
      assert.equal(countTbodyRows(html), SUMMARY_ROWS.length);
      const row = extractRow(html, 'Contacto Uno');
      const cells = cellsOf(row);
      // bPartner, current, days30, days60, days90, days120, days150plus(last bucket), total, credits, net
      assert.equal(cells[0], 'Contacto Uno');
      assert.equal(Number(cells[cells.length - 3]), 1000); // total
      assert.equal(Number(cells[cells.length - 2]), 50); // credits
      assert.equal(Number(cells[cells.length - 1]), 950); // net
    });

    it('CSV: one line per contact, using the row own aggregate total/credits/net', () => {
      const csv = renderCsv(artifactDir, { rows: SUMMARY_ROWS, showDetails: false });
      const lines = csv.split('\n').filter((l) => l.trim() !== '').slice(1);
      assert.equal(lines.length, SUMMARY_ROWS.length);
      const line = lines.find((l) => l.includes('Contacto Dos'));
      assert.ok(line);
      const fields = line.split(',');
      assert.equal(Number(fields[fields.length - 3]), 500); // total
      assert.equal(Number(fields[fields.length - 2]), 20); // credits
      assert.equal(Number(fields[fields.length - 1]), 480); // net
    });
  });
}
