/**
 * ETP-5013 — bug: `report-general-ledger`'s `template-excel.hbs` and
 * `template-csv.hbs` rendered the 4 dimension columns (Contacto/Producto/
 * Proyecto/Centro de costos) UNCONDITIONALLY, ignoring the `showDimensions`
 * toggle — even when the user generated the report with "Mostrar dimensiones
 * contables" OFF, the exported Excel/CSV still carried those columns as if
 * it were on. `template.hbs` (HTML/PDF) already gated them correctly with
 * `{{#ifCond meta.params.showDimensions '===' 'true'}}`; the excel/csv
 * templates simply never got the same guard.
 *
 * `report-journal-entries`'s sibling excel/csv templates already guard
 * `showDimensions` correctly (see `report-journal-entries-show-options.test.js`)
 * — this report was the only one missing it. Same render-path pattern as
 * that sibling test: `template-excel.hbs` compiles like the HTML/PDF path
 * (plain Handlebars.compile), `template-csv.hbs` goes through the jsreport
 * 'text' recipe path (buildJsreportHelpersString + `new Function`), mirroring
 * exactly what report-api.js does for each format.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import Handlebars from 'handlebars';
import { registerReportHelpers, buildJsreportHelpersString } from '../../../templates/reports/helpers/report-html-helpers.js';

const ARTIFACT_DIR = resolve(import.meta.dirname, '../../../artifacts/report-general-ledger');

const META_BASE = {
  title: 'General Ledger',
  ui: { records: 'records', total: 'Total', generatedBy: 'Generated by Schema Forge' },
  labels: {
    value: 'Código',
    name: 'Cuenta',
    dateacct: 'Fecha',
    amtacctdr: 'Debe',
    amtacctcr: 'Haber',
    bPartnerId: 'DIM CONTACT LABEL',
    productId: 'DIM PRODUCT LABEL',
    projectId: 'DIM PROJECT LABEL',
    costCenterId: 'DIM COST CENTER LABEL',
  },
  descriptionLabel: 'Descripción',
};

const ROWS = [
  {
    value: '35000000',
    name: 'Productos terminados A',
    dateacct: '2026-08-26',
    amtacctdr: 0,
    amtacctcr: 640.52,
    groupbyname: 'Juan Perez',
    bpname: 'DIM CONTACT VALUE',
    productname: 'DIM PRODUCT VALUE',
    projectname: 'DIM PROJECT VALUE',
    costcentername: 'DIM COST CENTER VALUE',
  },
];

function renderExcelLike(showDimensions) {
  const hb = Handlebars.create();
  const helpersCode = readFileSync(resolve(ARTIFACT_DIR, 'helpers.js'), 'utf8');
  registerReportHelpers(hb, helpersCode);
  const templateSrc = readFileSync(resolve(ARTIFACT_DIR, 'template-excel.hbs'), 'utf8');
  const template = hb.compile(templateSrc);
  return template({
    meta: { ...META_BASE, params: { showDimensions: String(showDimensions) } },
    rows: ROWS,
  });
}

describe('report-general-ledger — template-excel.hbs dimension columns (ETP-5013)', () => {
  it('omits the 4 dimension columns (header + value) when showDimensions=false', () => {
    const html = renderExcelLike(false);
    assert.doesNotMatch(html, /DIM CONTACT LABEL/);
    assert.doesNotMatch(html, /DIM PRODUCT LABEL/);
    assert.doesNotMatch(html, /DIM PROJECT LABEL/);
    assert.doesNotMatch(html, /DIM COST CENTER LABEL/);
    assert.doesNotMatch(html, /DIM CONTACT VALUE/);
    assert.doesNotMatch(html, /DIM PRODUCT VALUE/);
    assert.doesNotMatch(html, /DIM PROJECT VALUE/);
    assert.doesNotMatch(html, /DIM COST CENTER VALUE/);
  });

  it('shows all 4 dimension columns (header + value) when showDimensions=true', () => {
    const html = renderExcelLike(true);
    assert.match(html, /DIM CONTACT LABEL/);
    assert.match(html, /DIM PRODUCT LABEL/);
    assert.match(html, /DIM PROJECT LABEL/);
    assert.match(html, /DIM COST CENTER LABEL/);
    assert.match(html, /DIM CONTACT VALUE/);
    assert.match(html, /DIM PRODUCT VALUE/);
    assert.match(html, /DIM PROJECT VALUE/);
    assert.match(html, /DIM COST CENTER VALUE/);
  });
});

// CSV goes through the jsreport render path (recipe 'text'): the helpers string
// sent to jsreport is built via buildJsreportHelpersString (canonical set +
// the report-specific `csvField` extra extracted from helpers.js), then
// evaluated with `new Function` — mirroring exactly what report-api.js does
// for the jsreport (pdf/xlsx/csv) branch, per report-jsreport-helpers-builder.test.js.
function renderCsv(showDimensions) {
  const helpersCode = readFileSync(resolve(ARTIFACT_DIR, 'helpers.js'), 'utf8');
  const built = buildJsreportHelpersString(helpersCode);
  const helperNames = [...built.matchAll(/^function\s+(\w+)\s*\(/gm)].map((m) => m[1]);
  // eslint-disable-next-line no-new-func
  const helpers = new Function(`${built}\nreturn { ${helperNames.join(', ')} };`)();

  const hb = Handlebars.create();
  for (const [name, fn] of Object.entries(helpers)) {
    hb.registerHelper(name, fn);
  }
  const templateSrc = readFileSync(resolve(ARTIFACT_DIR, 'template-csv.hbs'), 'utf8');
  const template = hb.compile(templateSrc);
  return template({
    meta: { ...META_BASE, params: { showDimensions: String(showDimensions) } },
    rows: ROWS,
  });
}

describe('report-general-ledger — template-csv.hbs dimension columns (ETP-5013)', () => {
  it('omits the 4 dimension columns (header + value) when showDimensions=false', () => {
    const csv = renderCsv(false);
    assert.doesNotMatch(csv, /DIM CONTACT LABEL/);
    assert.doesNotMatch(csv, /DIM PRODUCT LABEL/);
    assert.doesNotMatch(csv, /DIM PROJECT LABEL/);
    assert.doesNotMatch(csv, /DIM COST CENTER LABEL/);
    assert.doesNotMatch(csv, /DIM CONTACT VALUE/);
    assert.doesNotMatch(csv, /DIM PRODUCT VALUE/);
    assert.doesNotMatch(csv, /DIM PROJECT VALUE/);
    assert.doesNotMatch(csv, /DIM COST CENTER VALUE/);
    // Same field count as the header on every data line (no trailing comma drift).
    const [headerLine, dataLine] = csv.trim().split('\n');
    assert.equal(headerLine.split(',').length, dataLine.split(',').length);
  });

  it('includes all 4 dimension columns (header + value) when showDimensions=true', () => {
    const csv = renderCsv(true);
    assert.match(csv, /DIM CONTACT LABEL/);
    assert.match(csv, /DIM PRODUCT LABEL/);
    assert.match(csv, /DIM PROJECT LABEL/);
    assert.match(csv, /DIM COST CENTER LABEL/);
    assert.match(csv, /DIM CONTACT VALUE/);
    assert.match(csv, /DIM PRODUCT VALUE/);
    assert.match(csv, /DIM PROJECT VALUE/);
    assert.match(csv, /DIM COST CENTER VALUE/);
    const [headerLine, dataLine] = csv.trim().split('\n');
    assert.equal(headerLine.split(',').length, dataLine.split(',').length);
  });
});
