import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import Handlebars from 'handlebars';
import { registerReportHelpers, buildJsreportHelpersString } from '../../../templates/reports/helpers/report-html-helpers.js';

// ETP-4899 — tax-report Excel/CSV export templates.
//
// tax-report is `"source": "neo"` (handler-driven, TaxReportHandler.java) and,
// until this change, reused template.hbs (the HTML/PDF template — grouped
// bands, blank filler cells, formatted text) for the Excel export too: every
// cell in the resulting .xlsx (including amounts) rendered as text (`t="str"`),
// not calculable. template-excel.hbs/template-csv.hbs fix this by dumping one
// flat, denormalized row per document, with `data-cell-type="number"` +
// unformatted values for amounts (verified against a real jsreport container
// to render `t="n"` numeric cells — see artifacts/tax-report/template-excel.hbs
// header comment).
//
// These tests compile the REAL .hbs files from disk (never a hardcoded copy)
// so a future edit that reintroduces text-typed amounts, or breaks the
// denormalization path (1-level-up `../taxName` for ungrouped docs vs.
// 2-levels-up `../../taxName` for grouped-by-contact docs, and the
// `../../rate` / `../bPartner` / `../bpTaxId` relative paths in the
// Summary-by-Rate sheet), fails here.

const ARTIFACT_DIR = resolve(import.meta.dirname, '../../../artifacts/tax-report');
const HELPERS_CODE = readFileSync(resolve(ARTIFACT_DIR, 'helpers.js'), 'utf8');

// Labels as they actually resolve in meta.labels (per buildContractLabels() in
// report-api.js): transactionType/bPartnerId come from contract.parameters,
// taxName/rate/taxBaseAmt/taxAmt/totalAmt from contract.columns, and
// docNo/docType/docDate/acctDate/country/region/noPartners/bpTaxId/
// taxCategory/purchasesPayments/salesReceipts from contract.labels — all
// verified directly against artifacts/tax-report/report-contract.json.
const LABELS = {
  en_US: {
    transactionType: 'Transaction Type',
    taxName: 'Tax Name',
    docNo: 'Doc No.',
    docType: 'Doc Type',
    docDate: 'Doc Date',
    acctDate: 'Acct Date',
    bPartnerId: 'Contact',
    country: 'Country',
    region: 'Region',
    taxBaseAmt: 'Tax Base',
    taxAmt: 'Tax Amount',
    totalAmt: 'Total',
    taxCategory: 'Tax Category',
    rate: 'Rate %',
    noPartners: 'No. Contacts',
    bpTaxId: 'Tax ID',
    purchasesPayments: 'Purchases / Payments',
    salesReceipts: 'Sales / Receipts',
  },
  es_ES: {
    transactionType: 'Tipo de Transacción',
    taxName: 'Impuesto',
    docNo: 'Nº Doc.',
    docType: 'Tipo Doc.',
    docDate: 'Fecha Doc.',
    acctDate: 'Fecha Contable',
    bPartnerId: 'Contacto',
    country: 'País',
    region: 'Región',
    taxBaseAmt: 'Base Imponible',
    taxAmt: 'Importe Impuesto',
    totalAmt: 'Importe Total',
    taxCategory: 'Categoría de Impuesto',
    rate: '% Impuesto',
    noPartners: 'Nº Contactos',
    bpTaxId: 'NIF/CIF',
    purchasesPayments: 'Compras / Pagos',
    salesReceipts: 'Ventas / Cobros',
  },
};

const META_BASE = {
  title: 'Tax Report',
  generatedAt: '2026-08-19T00:00:00.000Z',
  recordCount: 2,
  ui: { records: 'records', total: 'Total', generatedBy: 'Generated by Schema Forge' },
};

// Detail: one tax group with a direct `docs` array (groupByBp=false) on the
// purchase side, and one tax group with `bpGroups[].docs` (groupByBp=true) on
// the sales side — this is deliberate: it exercises BOTH denormalization
// depths (1 level up vs. 2 levels up) AND both transaction-type row labels in
// the same render.
const ROWS_DETAIL = {
  purchase: {
    detail: [
      {
        taxId: 'tax-vat21',
        taxName: 'VAT 21% (ungrouped)',
        taxBaseAmt: 100.5,
        taxAmt: 21.1,
        totalAmt: 121.6,
        docs: [
          {
            invoiceId: 'inv-1',
            docNo: 'INV-001',
            docType: 'API',
            docDate: '2026-08-01',
            acctDate: '2026-08-02',
            bPartner: 'Proveedor, SA "grande"',
            bpCountry: 'ES',
            bpRegion: 'Madrid',
            taxBaseAmt: 100.5,
            taxAmt: 21.1,
            totalAmt: 121.6,
          },
        ],
        bpGroups: [],
      },
    ],
  },
  sales: {
    detail: [
      {
        taxId: 'tax-vat10',
        taxName: 'VAT 10% (grouped)',
        taxBaseAmt: 200,
        taxAmt: 20,
        totalAmt: 220,
        docs: [],
        bpGroups: [
          {
            bPartnerId: 'bp-1',
            bPartner: 'Cliente Dos',
            taxBaseAmt: 200,
            taxAmt: 20,
            totalAmt: 220,
            docs: [
              {
                invoiceId: 'inv-2',
                docNo: 'ARI-002',
                docType: 'ARI',
                docDate: '2026-08-05',
                acctDate: '2026-08-06',
                bPartner: 'Cliente Dos',
                bpCountry: 'FR',
                bpRegion: 'Paris',
                taxBaseAmt: 200,
                taxAmt: 20,
                totalAmt: 220,
              },
            ],
          },
        ],
      },
    ],
  },
};

function renderExcel(rows, locale = 'en_US') {
  const hb = Handlebars.create();
  registerReportHelpers(hb, HELPERS_CODE);
  const templateSrc = readFileSync(resolve(ARTIFACT_DIR, 'template-excel.hbs'), 'utf8');
  const template = hb.compile(templateSrc);
  return template({
    css: '',
    meta: { ...META_BASE, labels: LABELS[locale] },
    rows,
  });
}

describe('tax-report — template-excel.hbs — Sheet 1 (Detail)', () => {
  for (const locale of ['en_US', 'es_ES']) {
    it(`denormalizes taxName from 1 level up (taxGroup.docs, groupByBp=false) and labels the row correctly [${locale}]`, () => {
      const html = renderExcel(ROWS_DETAIL, locale);
      const rowIdx = html.indexOf('INV-001');
      assert.ok(rowIdx !== -1, 'expected the ungrouped doc row to be present');
      const row = html.slice(html.lastIndexOf('<tr>', rowIdx), html.indexOf('</tr>', rowIdx));
      assert.match(row, /VAT 21% \(ungrouped\)/, 'taxName must be denormalized from the parent taxGroup');
      assert.match(row, new RegExp(LABELS[locale].purchasesPayments.replace(/[/]/g, '\\/')));
    });

    it(`denormalizes taxName from 2 levels up (taxGroup.bpGroups[].docs, groupByBp=true) and labels the row correctly [${locale}]`, () => {
      const html = renderExcel(ROWS_DETAIL, locale);
      const rowIdx = html.indexOf('ARI-002');
      assert.ok(rowIdx !== -1, 'expected the grouped-by-bp doc row to be present');
      const row = html.slice(html.lastIndexOf('<tr>', rowIdx), html.indexOf('</tr>', rowIdx));
      assert.match(row, /VAT 10% \(grouped\)/, 'taxName must be denormalized from 2 levels up (taxGroup, not bpGroup)');
      assert.match(row, new RegExp(LABELS[locale].salesReceipts.replace(/[/]/g, '\\/')));
    });

    it(`amount cells are numeric (data-cell-type="number") with RAW unformatted values [${locale}]`, () => {
      const html = renderExcel(ROWS_DETAIL, locale);
      // Raw dot-decimal, never the es-ES-formatted "100,50".
      assert.match(html, /<td data-cell-type="number">100\.5<\/td>/);
      assert.match(html, /<td data-cell-type="number">21\.1<\/td>/);
      assert.match(html, /<td data-cell-type="number">121\.6<\/td>/);
      assert.doesNotMatch(html, /100,5/, 'amounts must never go through formatCurrency (es-ES comma decimal)');
    });
  }
});

describe('tax-report — template-excel.hbs — Sheet 2 (Summary by Tax Category)', () => {
  const rows = {
    purchase: {
      summaryByCategory: [
        {
          taxCategoryId: 'cat-1',
          taxCategoryName: 'General Category',
          taxes: [
            { taxId: 'tax-vat21', taxName: 'VAT 21%', rate: 21, taxBaseAmt: 1000, taxAmt: 210, totalAmt: 1210, bpCount: 3 },
          ],
        },
      ],
    },
    sales: { summaryByCategory: [] },
  };

  it('flattens (category, tax) pairs with the category name denormalized from 1 level up', () => {
    const html = renderExcel(rows);
    assert.match(html, /General Category/);
    assert.match(html, /VAT 21%/);
    assert.match(html, /<td data-cell-type="number">21<\/td>/); // rate
    assert.match(html, /<td data-cell-type="number">1000<\/td>/);
    assert.match(html, /<td data-cell-type="number">210<\/td>/);
    assert.match(html, /<td data-cell-type="number">1210<\/td>/);
    assert.match(html, /<td data-cell-type="number">3<\/td>/); // bpCount
    assert.match(html, /Purchases \/ Payments/);
  });
});

describe('tax-report — template-excel.hbs — Sheet 3 (Summary by Tax Rate)', () => {
  // `rate` deliberately differs from any per-tax value the row could
  // accidentally leak from — proves the template resolves `../../rate`
  // (the summaryByRate bucket) and not something reachable at the `taxes`
  // level itself.
  const rows = {
    purchase: { summaryByRate: [] },
    sales: {
      summaryByRate: [
        {
          rate: 21,
          bpCount: 1,
          taxBaseAmt: 500,
          taxAmt: 105,
          totalAmt: 605,
          bpGroups: [
            {
              bPartnerId: 'bp-9',
              bPartner: 'Contacto Tasa',
              bpTaxId: 'B12345678',
              taxes: [
                { taxId: 'tax-vat21', taxName: 'VAT 21%', taxBaseAmt: 500, taxAmt: 105, totalAmt: 605, bpCount: 1 },
              ],
            },
          ],
        },
      ],
    },
  };

  it('resolves rate from 2 levels up (../../rate) and bPartner/bpTaxId from 1 level up (../bPartner, ../bpTaxId)', () => {
    const html = renderExcel(rows);
    const rowIdx = html.indexOf('B12345678');
    assert.ok(rowIdx !== -1, 'expected the bpTaxId to be present');
    const row = html.slice(html.lastIndexOf('<tr>', rowIdx), html.indexOf('</tr>', rowIdx));
    assert.match(row, /Contacto Tasa/, 'bPartner must resolve from the bpGroups level (../bPartner)');
    assert.match(row, /<td data-cell-type="number">21<\/td>/, 'rate must resolve from the summaryByRate level (../../rate)');
    assert.match(row, /VAT 21%/);
    assert.match(row, /Sales \/ Receipts/);
  });
});

// ── CSV (jsreport render path, recipe 'text') ───────────────────────────────
//
// Mirrors report-journal-entries-show-options.test.js: builds the helpers
// string the same way report-api.js does for jsreport (canonical set +
// report-specific `csvField` extracted from helpers.js), evaluates it via
// `new Function`, and registers on a fresh Handlebars instance.

function renderCsv(rows, locale = 'en_US') {
  const built = buildJsreportHelpersString(HELPERS_CODE);
  const helperNames = [...built.matchAll(/^function\s+(\w+)\s*\(/gm)].map((m) => m[1]);
  // eslint-disable-next-line no-new-func
  const helpers = new Function(`${built}\nreturn { ${helperNames.join(', ')} };`)();

  const hb = Handlebars.create();
  for (const [name, fn] of Object.entries(helpers)) {
    hb.registerHelper(name, fn);
  }
  const templateSrc = readFileSync(resolve(ARTIFACT_DIR, 'template-csv.hbs'), 'utf8');
  const template = hb.compile(templateSrc);
  return template({
    meta: { ...META_BASE, labels: LABELS[locale] },
    rows,
  });
}

describe('tax-report — template-csv.hbs', () => {
  it('escapes a contact name with an embedded comma and double quote (real quoting, no &quot; leak)', () => {
    const csv = renderCsv(ROWS_DETAIL);
    assert.match(csv, /"Proveedor, SA ""grande"""/, 'expected doubled internal quotes, wrapped in quotes');
    assert.doesNotMatch(csv, /&quot;/, 'csvField output must never be HTML-escaped — the template must use {{{ }}}, not {{ }}');
  });

  it('includes both the ungrouped (docs) and grouped-by-bp (bpGroups.docs) rows', () => {
    const csv = renderCsv(ROWS_DETAIL);
    assert.match(csv, /INV-001/);
    assert.match(csv, /ARI-002/);
    assert.match(csv, /VAT 21% \(ungrouped\)/);
    assert.match(csv, /VAT 10% \(grouped\)/);
  });

  it('formats dates via formatDateDisplay (dd-mm-yyyy) and prints raw (unformatted) amounts', () => {
    const csv = renderCsv(ROWS_DETAIL);
    assert.match(csv, /01-08-2026/); // docDate 2026-08-01 -> dd-mm-yyyy
    assert.match(csv, /02-08-2026/); // acctDate 2026-08-02
    assert.match(csv, /100\.5/);
    assert.doesNotMatch(csv, /100,5/, 'amounts must never go through formatCurrency in the CSV export');
  });

  it('exports ONLY the Detail data — no Summary-by-Category or Summary-by-Rate content', () => {
    const rowsWithSummaries = {
      ...ROWS_DETAIL,
      purchase: {
        ...ROWS_DETAIL.purchase,
        summaryByCategory: [{ taxCategoryId: 'cat-x', taxCategoryName: 'SHOULD_NOT_APPEAR_CATEGORY', taxes: [] }],
        summaryByRate: [{ rate: 21, bpGroups: [{ bPartnerId: 'bp-x', bPartner: 'SHOULD_NOT_APPEAR_BP', bpTaxId: 'SHOULD_NOT_APPEAR_TAXID', taxes: [] }] }],
      },
    };
    const csv = renderCsv(rowsWithSummaries);
    assert.doesNotMatch(csv, /SHOULD_NOT_APPEAR/);
  });

  it('header row uses translated labels [es_ES]', () => {
    const csv = renderCsv(ROWS_DETAIL, 'es_ES');
    assert.match(csv, /^Tipo de Transacción,Impuesto,Nº Doc\.,Tipo Doc\.,Fecha Doc\.,Fecha Contable,Contacto,País,Región,Base Imponible,Importe Impuesto,Importe Total/m);
  });

  it('header row uses translated labels [en_US]', () => {
    const csv = renderCsv(ROWS_DETAIL, 'en_US');
    assert.match(csv, /^Transaction Type,Tax Name,Doc No\.,Doc Type,Doc Date,Acct Date,Contact,Country,Region,Tax Base,Tax Amount,Total/m);
  });
});
