import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { useAuth } from '@/auth/AuthContext.jsx';
import { WindowLabelsProvider } from '@/i18n';

// ETP-4300 feature flag (build-time). When off (default), windows render exactly
// as before: no per-window label slice is loaded and no provider is mounted.
// When on, the window's gitignored `labels.js` slice (generated by the Vite
// prebuild) is loaded and provided to the subtree. Flipped on in 2B.5 to measure.
const SLICED_LABELS = import.meta.env.VITE_SLICED_LABELS === 'true';

export default function WindowLoader({ windowMap, apiBaseUrl }) {
  const { windowName, recordId } = useParams();
  const { token } = useAuth();
  const [Component, setComponent] = useState(null);
  const [slice, setSlice] = useState(null);
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    setError(null);
    setComponent(null);
    setSlice(null);

    const windowConfig = windowMap[windowName];
    if (!windowConfig) {
      setError(`Window "${windowName}" not found`);
      setLoading(false);
      return;
    }

    // Load the window component and (when enabled) its per-window label slice in
    // parallel. The slice is a build-time artifact; a window without one simply
    // gets a null slice and resolves labels from the shared dictionary as before.
    const loadComponent = windowConfig.loader();
    const loadSlice = SLICED_LABELS
      ? import(`@generated/${windowName}/generated/web/${windowName}/labels.js`)
          .then(mod => mod.default)
          .catch(() => null)
      : Promise.resolve(null);

    Promise.all([loadComponent, loadSlice])
      .then(([mod, sliceData]) => {
        setComponent(() => mod.default);
        setSlice(sliceData);
        setLoading(false);
      })
      .catch(err => {
        setError(`Failed to load window "${windowName}": ${err.message}`);
        setLoading(false);
      });
  }, [windowName, windowMap]);

  if (loading) {
    return <div className="flex items-center justify-center h-64 text-muted-foreground">Loading...</div>;
  }

  if (error) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-center">
          <p className="text-destructive font-medium">{error}</p>
          <p className="text-sm text-muted-foreground mt-2">Check that the component has been generated.</p>
        </div>
      </div>
    );
  }

  if (!Component) return null;

  // WindowLabelsProvider is mounted at the loader boundary so the WHOLE window
  // subtree — generated components AND custom siblings — can resolve sliced labels.
  // With a null slice (flag off or no slice for this window) it is a no-op pass-through.
  return (
    <WindowLabelsProvider slice={slice} data-testid="WindowLabelsProvider__f59d7c">
      <Component
        token={token}
        apiBaseUrl={`${apiBaseUrl}/${windowName}`}
        window={windowMap[windowName]}
        windowName={windowName}
        recordId={recordId}
        data-testid="Component__f59d7c" />
    </WindowLabelsProvider>
  );
}
